"""Local reviewable manifest preparation; no provider/source/DB calls."""
import hashlib,json,sys
from pathlib import Path
ROOT=Path('/tmp/capacity75-admission-20261008')
BASE='a6c080902895922ba60c4161d417255006b2bd1f'
p=Path('/tmp/capacity75-read-20261008/admission-preflight-20261008T045946.json')
live=json.loads(p.read_text())
assert live['source_sha']==BASE and live['target']=='staging'
manifest=json.loads((ROOT/'docs/agent/STAGING_MISSION.json').read_text())
manifest['mission']='Bound staging Yuyu claim-contention wait and deliver the guarded ten-service fleet; original source envelope and RAW writers OFF'
manifest['classification']='AMBER'
manifest['impacts']=[{'files':['services/api/app/services/freshness_queue.py','services/api/app/services/freshness_integration.py','services/api/tests/test_freshness_claim_wait_postgres.py','docs/agent/YUYU_CLAIM_WAIT.md','docs/agent/evidence/yuyu-claim-wait-preflight-20261008.json'],'effects':['application','tests','documentation','staging_deployment','infrastructure'],'reason':'Bound explicit four-slot contention recovery to six five-second waits inside the unchanged execution deadline. Native rollout to ten existing staging collectors requires AMBER fleet preflight. Preserve max16, atomic cap4, request budgets, pacing, original crons and writerOFF; no new jobs, mapping decisions, schema or history writes.'}]
collectors=[r for r in live['flags'] if r['name'].startswith('yuyutei-collector-shard-') or r['name']=='snkrdunk-collector']
rows=[{'name':r['name'],'service_id':r['service_id'],'recovery_deployment_id':r['deployment_id']} for r in collectors]
assert len(rows)==10
manifest['deployment_verification']['collector_services']=rows
manifest['deployment_verification'].pop('yuyu_cadence_profile',None)
manifest['deployment_verification'].pop('raw_dependency_migration',None)
impact=manifest['safeguards']['impact']
impact.update({'resources':[{'name':'Staging Postgres (read-only fingerprint, no migration)','project_id':'c613898d-bf03-43a6-8813-761f72e1c00a','environment_id':'05d1eac2-510d-4bd3-999e-fea9ead766b7','service_id':'08c557d4-9d74-43fa-a0ac-5a909e731f4e'},{'name':'Staging API','service_id':'5290becf-6956-4c5c-ab16-01d865587e07'},*rows],'routes':['Existing admitted ordinary RAW and discovery queue; no manual source invocation'],'dependencies':['f9/e8 protected RAW ledger/readers/portable backup19 remain compatible; original nine shards and SNKR singleton unchanged'],'deployment_impact':'Native API/frontend and ten existing collector image updates. Complete preflight pins original crons, current-source naturally adopted recovery images, staging destination, OFF flags, ledger hashes, source budgets and actionable RAW freshness. No new services/config/cron/budget/pacing/writer/mapping/schema mutations. Await independent actual-current natural components, not CLI metadata alone.','database_writes':0,'source_requests':0,'estimated_runtime_minutes':90})
manifest['safeguards']['recovery']={'artifact':BASE,'procedure':'Keep all13 writer flagsOFF and f9 schema/readers/ledger unchanged. Native revert of this bounded code/manifest restores retained PR79 API source. If containment is needed, redeploy only the ten exact staging recovery image IDs listed here (live canRedeploy verified), preserving cron/start commands and f9. No obsolete e8 full delivery or RAW expansion. Deployer never invokes Run Now; ordinary source execution stays scheduled.','trigger':'source denial or duplicate/uncontrolled request, wrong physical identity or integrity failure, lost ownership/lease/reservation leak, unexpected writer activation, actionable24h freshness regression or retry exceeding30seconds/execution deadline','backup':'Release writes no schema or historical RAW. Original16 ledger/hash/length pairs and protected15 encodings match preserved independent plaintext audit; f9 and portable backup19 compatible. All ten retained successful deployment IDs are destination-pinned and live canRedeploy=true. Retain all evidence and current state; no deletion or historical expansion.','validation':['services/api/tests/test_freshness_claim_wait_postgres.py','services/api/tests/test_freshness_queue_postgres.py','docs/agent/YUYU_CLAIM_WAIT.md','docs/agent/evidence/yuyu-claim-wait-preflight-20261008.json']}
manifest['safeguards']['verification']={'required_checks':['engineering-gate'],'post_change':['scripts/verify_staging_delivery.py','scripts/verify_snkr_published_discovery_component.py','scripts/verify_yuyu_raw_reader_component.py','scripts/generate_staging_state.py'],'observation_window':'Strict delivery artifact plus all10 actual new-source completed natural receipts under original schedules. Then measure positive RAW, contention waits, aggregate active claims<=4, zero denials/duplicates/leaks, budget<=bounds and RAW recurrence<=24h across a busy window. Empty SNKR turns establish image adoption only. No compression/cadence/NEW100 activation until separate fresh AMBER safeguards pass.'}
evidence={'target':'staging','classification':'AMBER','before_sha':BASE,'observed_at':live['observed_at'],'live_preflight_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'live_preflight':live,'validation':{'mock_queue_adapters_retry_health_tests_passed':105,'focused_contention_tests_after_constants':10,'source_http_in_tests':0,'full_native_engineering_required':True},'retry_bound_seconds':30,'retry_count':6,'retry_seconds':5,'active_claim_limit':4,'max_work':16,'runtime_deadline_unchanged':True,'cron_changes':0,'source_budget_changes':0,'writer_activations':0,'manual_source_jobs':0,'mapping_writes':0,'migrations':0,'production_accessed':False,'pr79':{'merge':BASE,'engineering_checks':'all passed','native_delivery':'guard refused GREEN fleet manifest before any collector upload','failed_ci':[37726361014,37726360626],'bounded_query_fleet_delivery_still_required':True},'forecast_correction':{'prior_execution_only_overlap':'superseded; preserved','provider_busy_includes':'scheduled startup plus runtime','thirty_second_wait_10minute_current_and_new100':'zero modeled deadline misses; NOT natural capacity proof','thirty_second_wait_10minute_added607':'61 misses','thirty_second_wait_5minute_added607':'166 misses','cadence_activation_authorized_by_this_release':False,'new100':'UNPLANNED; storage and natural capacity gates remain'},'post_change':manifest['safeguards']['verification'],'recovery':manifest['safeguards']['recovery']}
(ROOT/'docs/agent/evidence/yuyu-claim-wait-preflight-20261008.json').write_text(json.dumps(evidence,indent=2)+'\n')
manifest['diff_sha256']='PENDING_COMMITTED_DIFF'
(ROOT/'docs/agent/STAGING_MISSION.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Prepared local AMBER fleet manifest and retained fresh preflight; commit/hash/policy validation still required.')
