"""create initial tables

Revision ID: 8962070c1565
Revises: 
Create Date: 2026-07-07 14:18:51.127136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8962070c1565'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_code', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_jp', sa.String(length=255), nullable=True),
    sa.Column('set_code', sa.String(length=32), nullable=False),
    sa.Column('rarity', sa.String(length=32), nullable=False),
    sa.Column('variant', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_code', 'set_code', 'rarity', 'variant', 'language', name='uq_cards_identity')
    )
    op.create_index(op.f('ix_cards_card_code'), 'cards', ['card_code'], unique=False)
    op.create_index(op.f('ix_cards_set_code'), 'cards', ['set_code'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('raw_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_snapshots_content_hash'), 'raw_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_snapshots_fetched_at'), 'raw_snapshots', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_raw_snapshots_source_id'), 'raw_snapshots', ['source_id'], unique=False)
    op.create_table('source_card_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_card_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('manual_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'source_id', name='uq_source_card_mappings_card_source')
    )
    op.create_index(op.f('ix_source_card_mappings_card_id'), 'source_card_mappings', ['card_id'], unique=False)
    op.create_index(op.f('ix_source_card_mappings_source_id'), 'source_card_mappings', ['source_id'], unique=False)
    op.create_table('price_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price_type', sa.String(length=32), nullable=False),
    sa.Column('price_jpy', sa.Integer(), nullable=False),
    sa.Column('condition_label', sa.String(length=64), nullable=True),
    sa.Column('stock_status', sa.String(length=64), nullable=True),
    sa.Column('listing_count', sa.Integer(), nullable=True),
    sa.Column('raw_snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_snapshot_id'], ['raw_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_observations_card_id'), 'price_observations', ['card_id'], unique=False)
    op.create_index(op.f('ix_price_observations_observed_at'), 'price_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_price_observations_source_id'), 'price_observations', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_observations_source_id'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_observed_at'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_card_id'), table_name='price_observations')
    op.drop_table('price_observations')
    op.drop_index(op.f('ix_source_card_mappings_source_id'), table_name='source_card_mappings')
    op.drop_index(op.f('ix_source_card_mappings_card_id'), table_name='source_card_mappings')
    op.drop_table('source_card_mappings')
    op.drop_index(op.f('ix_raw_snapshots_source_id'), table_name='raw_snapshots')
    op.drop_index(op.f('ix_raw_snapshots_fetched_at'), table_name='raw_snapshots')
    op.drop_index(op.f('ix_raw_snapshots_content_hash'), table_name='raw_snapshots')
    op.drop_table('raw_snapshots')
    op.drop_table('sources')
    op.drop_index(op.f('ix_cards_set_code'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_code'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
