"""add snkrdunk discovery and candidates tables

Revision ID: 95e04918e3c1
Revises: 8962070c1565
Create Date: 2026-07-08 05:58:15.926993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e04918e3c1'
down_revision: Union[str, Sequence[str], None] = '8962070c1565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snkrdunk_discovery_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='running', nullable=False),
    sa.Column('seed_url', sa.String(length=1024), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('candidates_found', sa.Integer(), server_default='0', nullable=False),
    sa.Column('candidates_matched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snkrdunk_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discovery_run_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('price_jpy', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('listing_count', sa.Integer(), nullable=True),
    sa.Column('condition_label', sa.String(length=128), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('normalized_title', sa.String(length=512), nullable=True),
    sa.Column('detected_card_code', sa.String(length=64), nullable=True),
    sa.Column('detected_set_code', sa.String(length=32), nullable=True),
    sa.Column('detected_rarity', sa.String(length=32), nullable=True),
    sa.Column('detected_variant', sa.String(length=64), nullable=True),
    sa.Column('match_status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('matched_card_id', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("match_status IN ('pending', 'auto_matched', 'needs_review', 'rejected')", name='ck_snkrdunk_candidates_match_status'),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['snkrdunk_discovery_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snkrdunk_candidates_detected_card_code'), 'snkrdunk_candidates', ['detected_card_code'], unique=False)
    op.create_index(op.f('ix_snkrdunk_candidates_discovery_run_id'), 'snkrdunk_candidates', ['discovery_run_id'], unique=False)
    op.create_index(op.f('ix_snkrdunk_candidates_match_status'), 'snkrdunk_candidates', ['match_status'], unique=False)
    op.create_index(op.f('ix_snkrdunk_candidates_source_url'), 'snkrdunk_candidates', ['source_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snkrdunk_candidates_source_url'), table_name='snkrdunk_candidates')
    op.drop_index(op.f('ix_snkrdunk_candidates_match_status'), table_name='snkrdunk_candidates')
    op.drop_index(op.f('ix_snkrdunk_candidates_discovery_run_id'), table_name='snkrdunk_candidates')
    op.drop_index(op.f('ix_snkrdunk_candidates_detected_card_code'), table_name='snkrdunk_candidates')
    op.drop_table('snkrdunk_candidates')
    op.drop_table('snkrdunk_discovery_runs')
    # ### end Alembic commands ###
